### ISSUE TITLE
Is the version of networkx ~= 3.1 in requirements.txt correct?

### ISSUE THREAD

**Issue by WanderingTroubadour** [SUSTech-HPCLab/CS305-2023Spring-Project#1]
![D_1 X$@OW {{V@G(QL@W)N](https://user-images.githubusercontent.com/40555599/235300651-f73e824f-63a3-4671-be5d-695e26f4cbe3.jpg)

 No matching distribution found.

**Comment by EricLee543** [comment]
I have updated the requirements.txt. There is no need for `networkx` in the latest version. Thanks for your issue
