### ISSUE TITLE
NAT bonus

### ISSUE THREAD

**Issue by Mandyyymeng** [SUSTech-HPCLab/CS305-2023Spring-Project#16]
NAT对网络地址转换的测试怎么运行，就是用什么模拟主机和内外网IP呢，用Python自带的功能写测试文件吗？虚拟机在project起到什么作用？bonus的NAT就是需要实现一个NAT路由器是吗，要写的包括test controller和NAT.py？

**Comment by EricLee543** [comment]
我没有考虑过如何在mininet中实现NAT,第一个问题可能需要你自己来想出解决方法。虚拟机是为了方便广大同学轻易地构建实验环境。bonus的实现都取决于你的想法，你需要向助教展示实验结果和方法，并写在报告里。
