### ISSUE TITLE
Can't receive arping message in controller

### ISSUE THREAD

**Issue by Leopold-Lee** [SUSTech-HPCLab/CS305-2023Spring-Project#4]
The document says the hosts send arping when connecting to the network, but my program didn't receive any related message in the `packet_in_handler` method of the controller, how's that happened? Is `packet_in_handler` the right place to handle arping?

**Comment by EricLee543** [comment]
You should provide more logs to illustrate the actions you did. You can check the code in `tests/switching_test/test_network.py`. There are `arping` commands. You can type this commands in mininet cli to help yourself debug.

**Comment by Leopold-Lee** [comment]
I try to use `arping` conmands but get error `unknow command`, what could be the possible reasons?
![image](https://user-images.githubusercontent.com/78646446/236669351-310504b2-daa2-43b6-b3b4-49b2a106a739.png)

**Comment by EricLee543** [comment]
You used a python function not a cmd. See this cmd `arping -c %s -A -I %s-eth0 %s' % (count, node.name, node.IP()`, change the %s into the host you want to test. `arping -c xxx` is a linux command.

**Comment by Leopold-Lee** [comment]
I solved the issue, I can't receive the arping because I hadn't install `arping` on my ubuntu
